import re

with open('/home/agents/GitHub/pravda/sources/primary/transcriptions/diplomatic/SRC-HADIACH-SEJM-1659-DIPLOMATIC.txt', 'r', encoding='utf-8') as f:
    full_text = f.read()

body = full_text.split('================================================================================')[1]
pacta_end = body.find('Approbacya kommissyj Hadyackiey.')
part_bc = body[pacta_end:]

def clean_txt(t):
    return re.sub(r'\s+', ' ', t).strip()

# Let us define the exact list of units in Part B/C
# Each unit has: unit_id, heading, page, article_num, actor, operator, object, terms

units_spec = [
    # Part B: Ratification & General Framework
    {
        "unit_id": "UNIT-SEJM1659-APPROBACYA",
        "heading": "Approbacya kommissyj Hadyackiey",
        "page": "p. 301",
        "claim_id": "HC-SEJM1659-APP-002A",
        "start_match": "2. Ponieważ woysko nasze Zaporoskie odrzn-",
        "end_match": "Salvis pactis z X. lego Mcią Kurfirsztem Brandeburczykiem.",
        "terms": "kommissyą Hadyacką de actu et data iey 16 Septemb. 1658, approbuiemy y za prawo wieczne mieć chcemy, in volumen legum inferuiemy, Salvis pactis z Kurfirsztem Brandeburczykiem",
        "actor": "Його Королівська Милість (Ян Казимир); Сенат; Посольська Ізба",
        "speaker": "CROWN & DIET",
        "operator": "RATIFIES / INSERTS / RESERVES",
        "object": "Офіційне схвалення Сеймом Гадяцької комісії 1658 р., внесення її до книги законів (Volumina Legum) як вічного права із застереженням трактатів із курфюрстом Бранденбурзьким."
    },
    {
        "unit_id": "UNIT-SEJM1659-APPROBACYA",
        "heading": "Approbacya kommissyj Hadyackiey",
        "page": "p. 301",
        "claim_id": "HC-SEJM1659-APP-002B",
        "start_match": "A chcąc wolności woyska tego",
        "end_match": "Kommissya do dobr cerkiewnych.",
        "terms": "wolności woyska Zaporoskiego wiecznie zachować, konstytucyą 1638 y skrypt ad archivum dany abroguiemy",
        "actor": "Його Королівська Милість; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFIRMS / ABROGATES",
        "object": "Скасування ординації 1638 р. та секретного запису до архіву як таких, що суперечать нинішній угоді й козацьким вольностям."
    },
    # Part C: Separate statutory acts
    {
        "unit_id": "UNIT-SEJM1659-DOBRA-CERKIEWNE",
        "heading": "Kommissya do dobr cerkiewnych",
        "page": "pp. 301–302",
        "claim_id": "HC-SEJM1659-CERK-003",
        "start_match": "8. Chcąc iako naybardziey w Państwach na-",
        "end_match": "Duchowni religiey Greckiey.",
        "terms": "Kommissarzow w Koronie z Senatu, z koła Poselskiego, w W. X. Lit., dobra cerkiewne pro iure et iustitia oddawać, securitatem waruiemy, violatores securitatis penis legum subesse",
        "actor": "Сеймові комісари для церковних дібр у Короні та ВКЛ",
        "speaker": "CROWN & DIET",
        "operator": "APPOINTS / REQUIRES / PROTECTS",
        "object": "Призначення персонального складу комісарів від Сенату й Посольської ізби в Короні та ВКЛ для передачі церковних маєтностей на засадах права і справедливості під загрозою судової кари."
    },
    {
        "unit_id": "UNIT-SEJM1659-DUCHOWNI-GRECCY",
        "heading": "Duchowni religiey Greckiey",
        "page": "p. 302",
        "claim_id": "HC-SEJM1659-CLERGY-004",
        "start_match": "4. Aby stan duchowny Grecki, in levipendium",
        "end_match": "Deklaracya łaski naszey woysku Zaporoskiemu.",
        "terms": "stan duchowny Grecki, w dobrach Krolewskich duchownych y szlacheckich od poddaństwa podatkow pańszczyzn podwod robocizn uwalniamy, pod iurysdykcyą pasterzow zostawali",
        "actor": "духовенство давньої грецької релігії; посідачі королівських, духовних і шляхетських дібр",
        "speaker": "CROWN & DIET",
        "operator": "EXEMPTS / RESERVES",
        "object": "Повне звільнення грецького духовенства у всіх маєтностях Корони, ВКЛ і Русі від феодального підданства, податків, панщини й робіт із підпорядкуванням виключно власним пастирям."
    },
    {
        "unit_id": "UNIT-SEJM1659-LASKA-WOYSKU",
        "heading": "Deklaracya łaski naszey woysku Zaporoskiemu",
        "page": "p. 302",
        "claim_id": "HC-SEJM1659-LASK-005",
        "start_match": "5. Takośmy nie dawno przed tym dła swey-",
        "end_match": "Nobilitacya Nam, y Rzpltey dobrze zasłużonych",
        "terms": "konstytucyą 1638 pokassowali byli, z poddaństwem nawrocili, przy wolnościach y przywileiach zachowuiemy, klemencyą naszą oświadczamy",
        "actor": "Його Королівська Милість; Військо Запорозьке",
        "speaker": "CROWN SIDE",
        "operator": "PARDONS / CONFIRMS",
        "object": "Декларація королівської ласки козакам за повернення до підданства та підтвердження їхніх давніх привілеїв після скасування ординації 1638 р."
    },
    {
        "unit_id": "UNIT-SEJM1659-NOB-ZAPOROSCY",
        "heading": "Nobilitacya Nam, y Rzpltey dobrze zasłużonych z woyska Zaporoskiego",
        "page": "p. 302",
        "claim_id": "HC-SEJM1659-NOB-GEN-006",
        "start_match": "6. Zachęcaiąc do usług naszych, y Rzpltey lu-",
        "end_match": "Approtacya Terechtimirowa.",
        "terms": "ludzi w dziele rycerskim, do kleynotu szlachectwa Polskiego przypuszczamy, przywileie authoritate Seymu approbuiemy",
        "actor": "заслужені особи з Війська Запорозького; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Сеймове затвердження загальної нобілітації заслужених військових людей із лав Війська Запорозького до польського шляхетства."
    },
    {
        "unit_id": "UNIT-SEJM1659-TERECHTIMIROW",
        "heading": "Approtacya Terechtimirowa",
        "page": "p. 302",
        "claim_id": "HC-SEJM1659-TERECH-007",
        "start_match": "7. Przychylaiąc się do przywileiow od Nay-",
        "end_match": "Danina wieczna Lubomla y Baru.",
        "terms": "monaster Terechtymirowski, miasteczko Terechtymirow, z przewozem y z szynkami, woysku Zaporoskiemu konferuiemy",
        "actor": "Трахтемирівський монастир; Військо Запорозьке; король",
        "operator": "CONFIRMS / CONFERS",
        "object": "Сеймове підтвердження надання містечка й монастиря Трахтемирів із перевозом та шинками у вічне володіння Війську Запорозькому."
    },
    {
        "unit_id": "UNIT-SEJM1659-DANINA-WYHOWSKI",
        "heading": "Danina wieczna Lubomla y Baru",
        "page": "pp. 302–303",
        "claim_id": "HC-SEJM1659-LUBBAR-008",
        "start_match": "8. Takowe bydź znayduiemy posługi Wielmo-",
        "end_match": "Danina Urodz: Danielowi Wyhowskiemu.",
        "terms": "Wielmożnego Iana na Wyhowie Wyhowskiego Hetmana, Starostwo Lubomelskie y Barskie prawem wiecznym y dziedzicznym conferuiemy",
        "actor": "Гетьман Іван Виговський та його нащадки; Сейм; король",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Вічне й спадкове надання Любомльського та Барського староств гетьману Івану Виговському за його визначні заслуги."
    },
    {
        "unit_id": "UNIT-SEJM1659-DANIEL-WYHOWSKI",
        "heading": "Danina Urodz: Danielowi Wyhowskiemu",
        "page": "p. 303",
        "claim_id": "HC-SEJM1659-DANWYH-009",
        "start_match": "9. Maiąc wzgląd na zasługi Urodzonego Da-",
        "end_match": "Danina Urodz: Konstantemu Wyhowskiemu.",
        "terms": "Daniela Wyhowskiego Koniuszego W. X. Lit., Starostwo Nowomiejskie y Stężyckie cum consensu sejmu conferuiemy",
        "actor": "Данило Виговський; Сейм; король",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Сеймове надання маєтностей і староств конюшому ВКЛ Данилу Виговському."
    },
    {
        "unit_id": "UNIT-SEJM1659-KONST-WYHOWSKI",
        "heading": "Danina Urodz: Konstantemu Wyhowskiemu",
        "page": "p. 303",
        "claim_id": "HC-SEJM1659-KONWYH-010",
        "start_match": "10. Wyświadczył Nam y Rzeczyposp: wier-",
        "end_match": "Deklaracya łaski Urodzonemu Ierzemu Chmielni-",
        "terms": "Konstanty Wyhowski, dobr Trzcieńca y Rzepiechowa conferuiemy",
        "actor": "Костянтин Виговський; Сейм; король",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Сеймове надання маєтностей Трщенця та Ржепєхова Костянтину Виговському."
    },
    {
        "unit_id": "UNIT-SEJM1659-CHMIELNICKI",
        "heading": "Deklaracya łaski Urodzonemu Ierzemu Chmielnickiemu",
        "page": "p. 303",
        "claim_id": "HC-SEJM1659-CHMIEL-011",
        "start_match": "11. Iako wszystko woysko Zaporoskie, do ła-",
        "end_match": "Dekłaracya łask Tymoszowi Nosaczowi.",
        "terms": "Ierzemu Chmielnickiemu, dobra Hać y inne dożywociem konferuiemy",
        "actor": "Юрій Хмельницький; король; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / PARDONS",
        "object": "Оголошення королівської ласки Юрію Хмельницькому та надання йому маєтностей у довічне володіння."
    },
    {
        "unit_id": "UNIT-SEJM1659-NOSACZ",
        "heading": "Dekłaracya łask Tymoszowi Nosaczowi",
        "page": "p. 303",
        "claim_id": "HC-SEJM1659-NOSACZ-012",
        "start_match": "12. Maiąc zaleconą sposobność do dzieł ry-",
        "end_match": "Danina Urodz: Hrehoremu Hułanickiemu.",
        "terms": "Tymosza Nosacza Oboźnego Woysk Zaporoskich, do kleynotu szlacheckiego przypuszczamy",
        "actor": "Тимофій Носач, генеральний обозний; Сейм; король",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація генерального обозного Війська Запорозького Тимоша Носача до шляхетського стану."
    },
    {
        "unit_id": "UNIT-SEJM1659-HULANICKI",
        "heading": "Danina Urodz: Hrehoremu Hułanickiemu",
        "page": "p. 303",
        "claim_id": "HC-SEJM1659-HULAN-013",
        "start_match": "18. Uważaiąc rycerskie odwagi, dzielność, za-",
        "end_match": "Danina Stęblowa.",
        "terms": "Hrehoremu Hułanickiemu Pułkownikowi Korsuńskiemu, dobra z zamkiem w dożywocie conferuiemy",
        "actor": "Григорій Гуляницький, ніжинський/корсунський полковник; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Сеймове надання маєтностей полковнику Григорію Гуляницькому за військову відвагу."
    },
    {
        "unit_id": "UNIT-SEJM1659-STEMBLOW",
        "heading": "Danina Stęblowa",
        "page": "p. 303",
        "claim_id": "HC-SEJM1659-STEMBL-014",
        "start_match": "14. Chcąc wierne usługi, Urodzonego Fedora",
        "end_match": "Dekłaracya łaski naszey Szlachetnym Sulimom.",
        "terms": "Fedora Wyhowskiego, Stęblow conferuiemy",
        "actor": "Федір Виговський; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Сеймове надання маєтності Стеблів Федору Виговському."
    },
    {
        "unit_id": "UNIT-SEJM1659-SULIMY",
        "heading": "Dekłaracya łaski naszey Szlachetnym Sulimom",
        "page": "pp. 303–304",
        "claim_id": "HC-SEJM1659-SULIM-015",
        "start_match": "15. Lubo o urodzeniu szlacheckim Stefana,",
        "end_match": "Nobilitacya Zarudnego.",
        "terms": "Sulimom, szlachectwo approbuiemy y dobra potwierdzamy",
        "actor": "шляхетний рід Сулим; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFIRMS",
        "object": "Підтвердження шляхетського статусу й прав на родові маєтності представників роду Сулим."
    },
    {
        "unit_id": "UNIT-SEJM1659-ZARUDNY",
        "heading": "Nobilitacya Zarudnego",
        "page": "p. 304",
        "claim_id": "HC-SEJM1659-ZARUD-016",
        "start_match": "16. Maiąc zalecone wierność y odwagi Sa-",
        "end_match": "Deklarac: łaski naszey Hreoremu Leśnickiemu.",
        "terms": "Samuela Zarudnego Sędziego woyskowego, do kleynotu szlachectwa Polskiego przypuszczamy",
        "actor": "Самійло Зарудний, військовий суддя; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація військового судді Самійла Зарудного до польського шляхетства."
    },
    {
        "unit_id": "UNIT-SEJM1659-LESNICKI",
        "heading": "Deklarac: łaski naszey Hreoremu Leśnickiemu",
        "page": "p. 304",
        "claim_id": "HC-SEJM1659-LESN-017",
        "start_match": "17. Iako wszystkich ludzi rycerskich zwykli-",
        "end_match": "Nobilitacya Wasiła Złotarenka Złotarzewskiego.",
        "terms": "Hrehorego Leśnickiego Pułkownika Mirhorodzkiego, do kleynotu szlacheckiego przypuszczamy",
        "actor": "Григорій Лісницький, миргородський полковник; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація миргородського полковника Григорія Лісницького до шляхетського стану."
    },
    {
        "unit_id": "UNIT-SEJM1659-ZLOTARENKO",
        "heading": "Nobilitacya Wasiła Złotarenka Złotarzewskiego",
        "page": "p. 304",
        "claim_id": "HC-SEJM1659-ZLOT-018",
        "start_match": "18. Uważając dzieła rycerskie Wasiła Złota-",
        "end_match": "Danina Kamionki y Meszney, Urodzonemu Prokopowi",
        "terms": "Wasiła Złotarenka do kleynotu szlachectwa Polskiego, Złotarzewskim zwać się będzie",
        "actor": "Василь Золотаренко; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RENAMES",
        "object": "Нобілітація Василя Золотаренка до польського шляхетства з наданням прізвища Золотажевський."
    },
    {
        "unit_id": "UNIT-SEJM1659-WERESCZAKA",
        "heading": "Danina Kamionki y Meszney, Urodzonemu Prokopowi Weresczacze, y nadanie tytułu Wiernosłow",
        "page": "p. 304",
        "claim_id": "HC-SEJM1659-WERESCZ-019",
        "start_match": "19. Przywiley dany Urodzoneinu Prokopowi",
        "end_match": "Nobilitacya Iana Kowalewskiego, Harasima,",
        "terms": "Prokopowi Weresczącze Komornikowi Granicznemu dobra Kamionki y Meszney, tytuł szlachecki Wiernosłow",
        "actor": "Прокіп Верещака; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Сеймове надання маєтностей Прокопу Верещаці та надання йому придомка/титулу Вєррословов."
    },
    {
        "unit_id": "UNIT-SEJM1659-KOWALEWSKI-GROUP",
        "heading": "Nobilitacya Iana Kowalewskiego, Harasima, y braciey iego Kapłońskich, Iwana Bohatyrowicza...",
        "page": "p. 304",
        "claim_id": "HC-SEJM1659-KOWAL-020",
        "start_match": "20. Chcąc ludzi rycerskich łaską naszą iako",
        "end_match": "Nobilitacya Iakima Samczenka.",
        "terms": "Kowalewskiego, Kapłońskich, Bohatyrowicza, Czekałowskich, Rudnickiego, Lisowca, Sokołowskiego, Słoninki kleynot szlachectwa, Skwirę y Romanowkę",
        "actor": "група козацької старшини (Ковалевський, Каплонські, Богатирович, Чекаловські, Рудницький, Лісовець, Соколовський, Слонинка); Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Групова нобілітація старшин і козаків до шляхетського стану із закріпленням маєтностей Сквира й Романівка."
    },
    {
        "unit_id": "UNIT-SEJM1659-SAMCZENKO",
        "heading": "Nobilitacya Iakima Samczenka",
        "page": "p. 304",
        "claim_id": "HC-SEJM1659-SAMCZ-021",
        "start_match": "21. Maiąc w dziele rycerskim zaleconego Ia-",
        "end_match": "Nobilitacya Matthyasza Papkiewicza,",
        "terms": "Iakima Samczenka do tytułu szlacheckiego, dożywocie Bereżany approbuiemy",
        "actor": "Яким Самченко; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація Якима Самченка та надання йому в довічне володіння маєтності Бережани."
    },
    {
        "unit_id": "UNIT-SEJM1659-PAPIEWICZ-GROUP",
        "heading": "Nobilitacya Matthyasza Papkiewicza, Hawryła Porywaia, y Zacharyasza Surty",
        "page": "p. 304",
        "claim_id": "HC-SEJM1659-PAPK-022",
        "start_match": "22. Na instancyą woyska naszego Zaporo-",
        "end_match": "Indygenat Daniela Qliwemberka.",
        "terms": "Matthyasza Papkiewicza Hawryła Porywaia Zacharyasza Surtę nobilituiemy",
        "actor": "Матвій Папкевич, Гаврило Поривай, Захарій Сурта; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація трьох старшин Війська Запорозького за клопотанням козацького війська."
    },
    {
        "unit_id": "UNIT-SEJM1659-OLIWEMBERK",
        "heading": "Indygenat Daniela Qliwemberka",
        "page": "p. 304",
        "claim_id": "HC-SEJM1659-OLIW-023",
        "start_match": "238. Urodzonego Daniela Oliwemberka, na in-",
        "end_match": "Nobilitacya lakuba y Iana Pekulickich,",
        "terms": "Daniela Oliwemberka za szlachcica Polskiego y indygenę za zgodą wszech Stanow przyimuiemy, iuramentum fidelitatis wykonał",
        "actor": "Данило Олівемберк; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "GRANTS-INDIGENATE / CONFIRMS",
        "object": "Надання польського індигенату Данилу Олівемберку за клопотанням козацького гетьмана після складення присяги вірності."
    },
    {
        "unit_id": "UNIT-SEJM1659-PEKULICCY-GROUP",
        "heading": "Nobilitacya lakuba y Iana Pekulickich, Bazylego y Kiryła Iskrzyckich",
        "page": "p. 304",
        "claim_id": "HC-SEJM1659-PEKUL-024",
        "start_match": "24. Zachęcaiąc do naszey y Rzeplitey usługi,",
        "end_match": "Nobilitacya Kiryła Andryiowicza.",
        "terms": "Iakuba y Iana Pekulickich Bazylego y Kiryła Iskrzyckich do kleynotu szlachectwa Polskiego przypuszczamy",
        "actor": "Яків та Іван Пекулицькі, Василь і Кирило Іскрицькі; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Сеймове надання шляхетства родинам Пекулицьких та Іскрицьких."
    },
    {
        "unit_id": "UNIT-SEJM1659-ANDRYIEWICZ",
        "heading": "Nobilitacya Kiryła Andryiowicza",
        "page": "p. 304",
        "claim_id": "HC-SEJM1659-ANDRY-025",
        "start_match": "25. Między inszymi z woyska Zaporoskiego,",
        "end_match": "Monaster Krechowski.",
        "terms": "Kiryłowi Andryiowiczowi nobilitacyą, przywiley na Soroczynie utwierdzamy",
        "actor": "Кирило Андрієвич, кошовий полковник; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація Кирила Андрієвича та закріплення за ним маєтності Сорочинці."
    },
    {
        "unit_id": "UNIT-SEJM1659-KRECHOW",
        "heading": "Monaster Krechowski",
        "page": "pp. 304–305",
        "claim_id": "HC-SEJM1659-KRECH-026",
        "start_match": "26. Fundatio dobr monastera Krechowskiego,",
        "end_match": "Danina Qycu Gonaszewskiemu.",
        "terms": "monastera Krechowskiego przy cerkwi Transfigurationis, fundatio approbuiemy",
        "actor": "Крехівський православний монастир; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFIRMS",
        "object": "Сеймове підтвердження фундушу та маєтностей Крехівського Преображенського монастиря."
    },
    {
        "unit_id": "UNIT-SEJM1659-GONASZEWSKI",
        "heading": "Danina Qycu Gonaszewskiemu",
        "page": "p. 305",
        "claim_id": "HC-SEJM1659-GONASZ-028",
        "start_match": "28. Z klemencyi naszey wrodzoney, oycu Go-",
        "end_match": "Nobilitacya Andrzeia Romanenka.",
        "terms": "oycu Gonaszewskiemu wieś Mytnicę conferuiemy",
        "actor": "отець Гонашевський; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Сеймове надання села Митниця отцю Гонашевському."
    },
    {
        "unit_id": "UNIT-SEJM1659-ROMANENKO",
        "heading": "Nobilitacya Andrzeia Romanenka",
        "page": "p. 305",
        "claim_id": "HC-SEJM1659-ROMAN-029",
        "start_match": "29. Do kleynotu szlachectwa Polskiego przy-",
        "end_match": "Nobilitacya Wasiła Mitczenka.",
        "terms": "Andrzeia Romanenka do szlachectwa przypuszczamy",
        "actor": "Андрій Романенко; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація Андрія Романенка до польського шляхетського стану."
    },
    {
        "unit_id": "UNIT-SEJM1659-MITCZENKO",
        "heading": "Nobilitacya Wasiła Mitczenka",
        "page": "p. 305",
        "claim_id": "HC-SEJM1659-MITCZ-030",
        "start_match": "380. Wasiła Mitczenka, w poczet szlachty Pol-",
        "end_match": "Nobilitacya Iana Mazarakiego.",
        "terms": "Wasiła Mitczenka w poczet szlachty Polskiey przyimuiemy",
        "actor": "Василь Мітченко; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Прийняття Василя Мітченка до кола польської шляхти."
    },
    {
        "unit_id": "UNIT-SEJM1659-MAZARAKI",
        "heading": "Nobilitacya Iana Mazarakiego",
        "page": "p. 305",
        "claim_id": "HC-SEJM1659-MAZAR-031",
        "start_match": "31. Na zalecenie Hetmana woysk naszych Za-",
        "end_match": "Danina Urodzonego Maziepy.",
        "terms": "Iana Mazarakiego do kleynotu szlachectwa przypuszczamy",
        "actor": "Іван Мазаракі; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація Івана Мазаракі за рекомендацією гетьмана."
    },
    {
        "unit_id": "UNIT-SEJM1659-MAZIEPA",
        "heading": "Danina Urodzonego Maziepy",
        "page": "p. 305",
        "claim_id": "HC-SEJM1659-MAZIEP-032",
        "start_match": "32. Maiąc wzgląd na wierne usługi Urodzo-",
        "end_match": "Nobilitacya Ostapha Feckowiocza.",
        "terms": "Adama Maziepy wieś Kamionkę conferuiemy",
        "actor": "Адам (Степан-Адам) Мазепа (батько Івана Мазепи); Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Сеймове надання села Кам'янка Адаму Мазепі за вірну службу."
    },
    {
        "unit_id": "UNIT-SEJM1659-FECKOWICZ",
        "heading": "Nobilitacya Ostapha Feckowiocza",
        "page": "p. 305",
        "claim_id": "HC-SEJM1659-FECK-033",
        "start_match": "38. Z dzieł rycerskich maiąc zaleconego Osta-",
        "end_match": "Nobilitacya Maxyma Bułyhy.",
        "terms": "Ostapha Feckowicza kleynot szlachectwa",
        "actor": "Остап Фецкович; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація козака Остапа Фецковича до шляхетства."
    },
    {
        "unit_id": "UNIT-SEJM1659-BULYHA",
        "heading": "Nobilitacya Maxyma Bułyhy",
        "page": "p. 305",
        "claim_id": "HC-SEJM1659-BULYH-034",
        "start_match": "34. Maiąc zaleconego z dzieł rycerskich Ma-",
        "end_match": "Nobilitacya Krzysztofa Wartereszowica Sło-",
        "terms": "Maxyma Bułyhę z woyska Zaporoskiego nobilituiemy",
        "actor": "Максим Булига, зятковецький сотник; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація козацького сотника Максима Булиги до шляхетства."
    },
    {
        "unit_id": "UNIT-SEJM1659-WARTERESZOWIC",
        "heading": "Nobilitacya Krzysztofa Wartereszowica Słoniewskiego",
        "page": "p. 305",
        "claim_id": "HC-SEJM1659-WART-035",
        "start_match": "35. W nagrodę zasługi Szlachetnego Krzy-",
        "end_match": "Nobilitacya Thimosza Ciciury.",
        "terms": "Krzysztofa Wartereszowica Słoniewskiego nobilituiemy",
        "actor": "Криштоф Вартерешович Слоневський; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація Криштофа Вартерешовича Слоневського."
    },
    {
        "unit_id": "UNIT-SEJM1659-CICIURA",
        "heading": "Nobilitacya Thimosza Ciciury",
        "page": "pp. 305–306",
        "claim_id": "HC-SEJM1659-CIC-036",
        "start_match": "86. Rycerskie odwagi Urodzonego Thymosza",
        "end_match": "Nobilitacya Bazylego Woytkiewicza.",
        "terms": "Thymosza Ciciury Pułkownika Pereiasławskiego nobilituiemy",
        "actor": "Тимофій Цицюра, переяславський полковник; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація переяславського полковника Тимоша Цицюри до шляхетського стану."
    },
    {
        "unit_id": "UNIT-SEJM1659-WOYTKIEWICZ",
        "heading": "Nobilitacya Bazylego Woytkiewicza",
        "page": "p. 306",
        "claim_id": "HC-SEJM1659-WOYTK-037",
        "start_match": "37. Aby się ludzie rycerscy z większą ocho-",
        "end_match": "Nobilitacya Bohdana Kaleniczenka.",
        "terms": "Bazylego Woytkiewicza nobilituiemy",
        "actor": "Василь Войткевич; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація Василя Войткевича до шляхетства."
    },
    {
        "unit_id": "UNIT-SEJM1659-KALENICZENKO",
        "heading": "Nobilitacya Bohdana Kaleniczenka",
        "page": "p. 306",
        "claim_id": "HC-SEJM1659-KALEN-038",
        "start_match": "38. Chcąc więcey cives odważnych tey Rze-",
        "end_match": "Nobilitacya Stefana Derżeniewskiego.",
        "terms": "Bohdana Kaleniczenka nobilituiemy",
        "actor": "Богдан Калениченко; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація Богдана Калениченка до шляхетського стану."
    },
    {
        "unit_id": "UNIT-SEJM1659-DERZENIEWSKI",
        "heading": "Nobilitacya Stefana Derżeniewskiego",
        "page": "p. 306",
        "claim_id": "HC-SEJM1659-DERZ-039",
        "start_match": "39. Przysposabiaiąc, dla dostoieństwa nasze-",
        "end_match": "Przysięga.",
        "terms": "Stefana Derżeniewskiego nobilituiemy",
        "actor": "Стефан Держенєвський; Сейм",
        "speaker": "CROWN & DIET",
        "operator": "CONFERS / RATIFIES",
        "object": "Нобілітація Стефана Держенєвського до шляхетства."
    },
    # OATHS SECTION
    {
        "unit_id": "UNIT-SEJM1659-PRZYSIEGA-INTRO",
        "heading": "Przysięga",
        "page": "p. 306",
        "claim_id": "HC-SEJM1659-OATH-GEN-040",
        "start_match": "40. Na utwierdzenie kommissyi między Nay-",
        "end_match": "Przysięga Imci X. Arcybiskupa Gnieżnieńskiego.",
        "terms": "kommissyi pod Hadiaczem, roty przysiąg od Stanow Rzpltey y woyska Zaporoskiego do prawa pospolitego wnosimy",
        "actor": "Сейм Речі Посполитої; сенатори, посли та козацькі депутати",
        "speaker": "CROWN & DIET",
        "operator": "MANDATES / INSERTS",
        "object": "Внесення до загального права рот урочистих присяг на непорушне дотримання Гадяцької угоди з обох сторін."
    },
    {
        "unit_id": "UNIT-SEJM1659-PRZYSIEGA-PRYMAS",
        "heading": "Przysięga Imci X. Arcybiskupa Gnieżnieńskiego",
        "page": "p. 306",
        "claim_id": "HC-SEJM1659-OATH-PRYM-041",
        "start_match": "41. Ia Wacław z Leszna, z Bożey łaski Ar-",
        "end_match": "Przysięga Imci X. Biskupa Wileńskiego.",
        "terms": "Wacław z Leszna Arcybiskup Gnieźnieński Primas, przysięgam Panu Bogu kommissyą pod Hadiaczem trzymać, dyspensacyi nie przyimować",
        "actor": "Вацлав Лещинський, архієпископ Гнєзненський, Примас Польщі",
        "speaker": "CLERGY (CATHOLIC PRIMATE)",
        "operator": "SWORES / BINDS",
        "object": "Текст урочистої присяги Примаса Польщі на вірне дотримання Гадяцької комісії без прийняття жодних церковних диспенсацій."
    },
    {
        "unit_id": "UNIT-SEJM1659-PRZYSIEGA-WILNO",
        "heading": "Przysięga Imci X. Biskupa Wileńskiego",
        "page": "p. 306",
        "claim_id": "HC-SEJM1659-OATH-WILN-042",
        "start_match": "42. Ia lan Zawisza Biskup Wileński, przy-",
        "end_match": "Przysięga Ich Mciow PP. Hetmanow.",
        "terms": "Ian Zawisza Biskup Wileński, kommissyą stwierdzam, żadnego rozgrzeszenia nie przyimuię",
        "actor": "Ян Завіша, єпископ Віленський",
        "speaker": "CLERGY (CATHOLIC BISHOP)",
        "operator": "SWORES / BINDS",
        "object": "Текст присяги єпископа Віленського від імені духовного стану ВКЛ на дотримання комісії."
    },
    {
        "unit_id": "UNIT-SEJM1659-PRZYSIEGA-HETMANI",
        "heading": "Przysięga Ich Mciow PP. Hetmanow",
        "page": "pp. 306–307",
        "claim_id": "HC-SEJM1659-OATH-HET-043",
        "start_match": "48. My Stanisław z Potoka Potocki, Woie-",
        "end_match": "Przysięga Ich Mciow PP. Pieczętarzow,",
        "terms": "Stanisław Potocki Hetman Wielki Koronny, Ierzy Lubomirski Hetman Polny, Paweł Sapieha Hetman Litewski, Wincenty Gosiewski, przysięgamy kommissyi dosięgać",
        "actor": "чотири гетьмани Корони та ВКЛ (Потоцький, Любомирський, Сапєга, Гонсєвський)",
        "speaker": "MILITARY COMMANDERS",
        "operator": "SWORES / BINDS",
        "object": "Текст присяги чотирьох коронних і литовських гетьманів на дотримання умов миру з Військом Запорозьким."
    },
    {
        "unit_id": "UNIT-SEJM1659-PRZYSIEGA-PIECZETARZE",
        "heading": "Przysięga Ich Mciow PP. Pieczętarzow",
        "page": "p. 307",
        "claim_id": "HC-SEJM1659-OATH-CHANC-044",
        "start_match": "44. My Mikołay Prażmowski, Kanclerz Wiel-",
        "end_match": "Przysięga IMci P. Marszałka Poselskiey Izby.",
        "terms": "Mikołay Prażmowski Kanclerz Koronny, Bogusław Leszczyński Podkanclerzy, Krzysztof Pac Kanclerz Litewski, Aleksander Naruszewicz, nic przeciwnego kommissyi nie pieczętować",
        "actor": "вищі канцлери й підканцлери обох народів (Пражмовський, Лещинський, Пац, Нарушевич)",
        "speaker": "CHANCELLORS",
        "operator": "SWORES / PLEDGES / PROHIBITS",
        "object": "Текст присяги канцлерів і підканцлерів Корони та ВКЛ ніколи не прикладати печатки до актів, що суперечать Гадяцькій комісії."
    },
    {
        "unit_id": "UNIT-SEJM1659-PRZYSIEGA-MARSZALEK",
        "heading": "Przysięga IMci P. Marszałka Poselskiey Izby",
        "page": "p. 307",
        "claim_id": "HC-SEJM1659-OATH-MARSZ-045",
        "start_match": "45. Ia lan Gniński, Podkomorzy Pomorski,",
        "end_match": "Iurament Posłow W. X. Ruskiego, y woysk Zapo- roskich.",
        "terms": "Ian Gniński Marszałek Izby Poselskiey imieniem wszytkiego Koła Poselskiego, kommissyą w całey powadze trzymać",
        "actor": "Ян Гнінський, маршалок Посольської ізби, від імені всього лицарського кола депутатів",
        "speaker": "SPEAKER OF PARLIAMENT",
        "operator": "SWORES / BINDS",
        "object": "Текст присяги маршалка Посольської ізби від імені всіх послів Сейму на непорушність укладеної угоди."
    },
    {
        "unit_id": "UNIT-SEJM1659-PRZYSIEGA-POSLOWIE-RUS",
        "heading": "Iurament Posłow W. X. Ruskiego, y woysk Zaporoskich",
        "page": "p. 307",
        "claim_id": "HC-SEJM1659-OATH-RUS-046",
        "start_match": "46. Także osobliwie na to od I. Wiel: Het-",
        "end_match": "Rezydenci przy boku naszym.",
        "terms": "Posłowie W. X. Ruskiego y woysk Zaporoskich, Nemirycz Leśnicki Wereszczaka Andryieczko Kosiński Hulanicki Zarudny Bułyha Ciciura, przysięgamy wierność Krolowi y Rzeczypospolitey, braterstwo z Koroną y W. X. Lit.",
        "actor": "посли Великого Князівства Руського та Війська Запорозького (Немирич, Лісницький, Верещака, Андрієвич, Зарудний, Булига, Цицюра та ін.)",
        "speaker": "COSSACK & RUTHENIAN ENVOYS",
        "operator": "SWORES / PLEDGES",
        "object": "Урочиста присяга послів Великого Князівства Руського та старшин Війська Запорозького на вірність королю Яну Казимиру, його наступникам і братерський союз із Короною та ВКЛ."
    },
    {
        "unit_id": "UNIT-SEJM1659-REZYDENCI",
        "heading": "Rezydenci przy boku naszym",
        "page": "p. 307",
        "claim_id": "HC-SEJM1659-REZYD-047",
        "start_match": "Rezydenci przy boku naszym.",
        "end_match": "==END==",
        "terms": "Rezydenci przy boku naszym na pierwsze pułroka, Biskup Kamieniecki Woiewoda Mścisławski Bełski Radomski, Arcy-Biskup Gnieźnieński",
        "actor": "сенатори-резиденти при королі (єпископи та воєводи за кварталами року)",
        "speaker": "CROWN & DIET",
        "operator": "APPOINTS / SCHEDULES",
        "object": "Призначення черговості сенаторів-резидентів при королівському дворі за кварталами року для здійснення поточного державного управління."
    }
]

print(f"Total Part B/C structured units: {len(units_spec)}")
